linters-settings:
  dupl:
    threshold: 100
  funlen:
    lines: 120
    statements: 60
  gci:
    local-prefixes: github.com/velmie/x/sqlconnection/mysql
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  gocyclo:
    min-complexity: 20
  goimports:
    local-prefixes: github.com/velmie/x/sqlconnection/mysql
  golint:
    min-confidence: 0
  gomnd:
    settings:
      mnd:
        # don't include the "operation" and "assign"
        checks: [argument,case,condition,return]
  govet:
    check-shadowing: true
  lll:
    line-length: 140
  maligned:
    suggest-new: true
  misspell:
    locale: US
  nolintlint:
    allow-leading-space: true # don't require machine-readable nolint directives (i.e. with no leading space)
    allow-unused: false # report any unused nolint directives
    require-explanation: false # don't require an explanation for nolint directives
    require-specific: false # don't require nolint directives to be specific about which linter is being skipped

linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - errcheck
    - funlen
    - gochecknoinits
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nolintlint
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - asasalint
    - asasalint
    - bidichk
    - contextcheck
    - dupl
    - durationcheck
    - errchkjson
    - exportloopref
    - forbidigo
    - gocognit
    - gocritic
    - grouper
    - importas
    - loggercheck
    - maintidx
    - makezero
    - nilerr
    - nilnil
    - prealloc
    - reassign
    - tagliatelle
    - tenv
    - usestdlibvars
    - rowserrcheck
    - revive


issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gomnd
        - funlen
        - gocyclo
        - lll
run:
  timeout: 5m

# golangci.com configuration
# https://github.com/golangci/golangci/wiki/Configuration
service:
  golangci-lint-version: 1.59.1 # use the fixed version to not introduce new linters unexpectedly
